apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
data:
  init.sql: |
    CREATE TABLE Users (
        login TEXT NOT NULL PRIMARY KEY,
        name TEXT NOT NULL,
        phone TEXT
    );