{
 "title": "Latency, RPS, Error Rate",
 "description": "Мониторинг задержки, запросов в секунду, ошибок",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency (quantile max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (job) (http_server_requests_seconds_bucket{job=\"spring-boot\", le=\"+Inf\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (quantile 0.99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{job=\"spring-boot\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency (quantile 0.5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{job=\"spring-boot\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RSP без фильтров",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"spring-boot\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"spring-boot\", status=~\"5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS (Requests Per Second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"spring-boot\", status=\"200\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (quantile 0.95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{job=\"spring-boot\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}