apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
type: Opaque
data:
  POSTGRES_DB: bXlkYXRhYmFzZQ== # имя созданной базы данных (mydatabase)
  POSTGRES_USER: VGVzdFVzZXI= # имя пользователя в base64 (TestUser)
  POSTGRES_PASSWORD: VGVzdFBhc3N3b3Jk # пароль пользователя в base64 (TestPassword)